tasks 91-104
maycatsby/ui-internship-lwo2 pull request #10
Opened 2019-05-15 20:07 UTC by maycatsby

2019-05-16 10:20 UTC, tkachukivan approved these changes

2019-05-16 10:20 UTC, tkachukivan commented on tasks/100_greatest-common-divisor/greatest-common-divisor.js
> +      continue;
what is the reason for this? if you omit this it will work the same

2019-05-16 10:20 UTC, tkachukivan commented on tasks/101_least-common-multiple/least-common-multiple.js
> +  for (let i = 1; i < 10; i++) {
up to 10? maybe there is other algorithm to do it, probably there is a formula with using greatestCommonDivisor

2019-05-16 10:20 UTC, tkachukivan commented on tasks/100_greatest-common-divisor/greatest-common-divisor.js
> +  let smallerNumber = Math.min(num1, num2);
take a look at Euclidean algorithm for this, it looks a bit better here

2019-05-16 10:20 UTC, tkachukivan commented on tasks/103_stack/stack.js
> +      newTop.prev = this.last; this.last = newTop;
new line?

2019-05-16 10:20 UTC, tkachukivan commented on tasks/91_inventory-update/inventory-update.js
> +      newInv.splice(index, 1);
it is not very good practice to modify parameters

2019-05-16 10:20 UTC, tkachukivan commented on tasks/95_pairwise/pairwise.js
> +      return arr[i] + cur === num && index !== i;
you can use just a for loop here and start from current index + 1, in this case you will not have to check for index !== i and you will not iterate array every iteration of loop above

2019-05-16 10:20 UTC, tkachukivan commented on tasks/96_how-many-differences-of-squares/how-many-differences-of-squares.js
> +  let counter = 0;
it is possible to solve without loop

2019-05-16 10:20 UTC, tkachukivan commented on tasks/99_fat-fingers/fat-fingers.js
> +  return arrayOfString.map((cur, ind) => {
you can use reduce here and it will allow for you omit first check and join function in the end

2019-05-17 09:59 UTC, tsvetkovv requested changes
Please take a look at Ivan's comments

2019-05-17 09:59 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +    return this.firstName = this.fullName.split(' ')[0];
it's bad practice when getter changes values

2019-05-17 09:59 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +}
Try to avoid keeping `this.fullName` and use two variables only: `firstName` and `lastName`.

2019-05-17 09:59 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +    this.fullName = fullName;
use already implemented setters

2019-05-17 20:59 UTC, tsvetkovv approved these changes

2019-05-17 20:59 UTC, Tsvetkovv commented on tasks/93_make-a-person/make-a-person.js
> +    this._lastName = fullName.split(' ')[1];
reuse fullName setter

2019-05-28 09:02 UTC, merged