task 2
maycatsby/ui-internship-lwo2 pull request #12
Opened 2019-05-28 09:30 UTC by maycatsby

link https://maycatsby.github.io/ui-internship-lwo2/HTML/task2/

2019-05-28 14:43 UTC, tkachukivan approved these changes
It would be more logical if checkboxes was selected by default and when you uncheck one you don't show values connected with this checkbox

2019-05-28 14:43 UTC, tkachukivan commented on HTML/task2/index.html
> +    <main class = 'wrapper'>
you don't need to use spaces in front and after `=` also generally there is a rule that in js we use single quotes and in html double, but at least keep consistency as you use both of them and it is not very good!!!

2019-05-28 14:43 UTC, tkachukivan commented on HTML/task2/index.html
> +                <label class = "label--red" for = 'red'>red</label>
why `--` when just `-` is completely ok, same below

2019-05-28 15:08 UTC, tsvetkovv requested changes
Please take a look at Ivan's comments

2019-05-30 08:56 UTC, tsvetkovv approved these changes

2019-05-30 08:56 UTC, Tsvetkovv commented on HTML/task2/style.css
> +    display: none;
Could you use one rule for 3 selectors? It reduces code duplication

2019-05-30 08:56 UTC, Tsvetkovv commented on HTML/task2/style.css
> +input[id="red"]:not(:checked) ~ .span-red {
`input#red`?

2019-07-12 07:25 UTC, merged