task3
maycatsby/ui-internship-lwo2 pull request #14
Opened 2019-05-28 09:43 UTC by maycatsby

link https://maycatsby.github.io/ui-internship-lwo2/HTML/task3/

2019-05-28 14:49 UTC, tkachukivan approved these changes

2019-05-28 14:49 UTC, tkachukivan commented on HTML/task3/index.html
> +                    <div class = 'line4'>Y</div>
You can think that I`m fascist a bit, but spaces :D

2019-05-28 14:49 UTC, tkachukivan commented on HTML/task3/style.css
> +    margin-bottom: 0.2rem;
order here different from order above, try to be consistent

2019-05-28 15:13 UTC, tsvetkovv requested changes
spaces, plz

2019-05-29 08:54 UTC, tsvetkovv approved these changes

2019-07-12 07:25 UTC, merged