task4
maycatsby/ui-internship-lwo2 pull request #16
Opened 2019-05-28 11:03 UTC by maycatsby

link https://maycatsby.github.io/ui-internship-lwo2/HTML/task4/

2019-05-28 15:04 UTC, tkachukivan requested changes
There is no visual difference if I filter something or not, when I check both checkboxes there is no records in table

2019-05-28 15:04 UTC, tkachukivan commented on HTML/task4/style.css
> +    width: 30%;
generally it is better to have one empty line between selectors
```
h2 {
    text-align: center;
    margin: 20px 0 40px 0;
}

main {
    margin: 0 auto;
    width: 30%;
}
```

2019-05-28 15:53 UTC, tsvetkovv approved these changes

2019-05-28 15:53 UTC, Tsvetkovv commented on HTML/task4/style.css
> +input[id="drinks"]:checked ~ table tbody .sweets,
so strange, why attribute selector?
`#drinks` - by id

2019-05-30 14:36 UTC, tkachukivan approved these changes

2019-07-12 07:25 UTC, merged