task1
maycatsby/ui-internship-lwo2 pull request #19
Opened 2019-05-29 10:11 UTC by maycatsby

link https://maycatsby.github.io/ui-internship-lwo2/HTML/task1/

2019-05-29 11:27 UTC, tsvetkovv requested changes

2019-05-29 11:27 UTC, Tsvetkovv commented on HTML/task1/index.html
> +    <table width='100%' height='100%' border='1px' cellspacing='0' cellpadding="5">
single-quote or double-quote? Should be consistent

2019-05-29 11:27 UTC, Tsvetkovv commented on HTML/task1/index.html
> +                    <ul>
Could you align this list to center?

2019-05-30 12:52 UTC, tsvetkovv approved these changes

2019-05-30 13:59 UTC, tkachukivan approved these changes

2019-07-12 07:24 UTC, merged