Mockup axit - task 1 JS
maycatsby/ui-internship-lwo2 pull request #26
Opened 2019-07-17 09:38 UTC by maycatsby

https://maycatsby.github.io/ui-internship-lwo2/HTML/mockup-axit/

2019-07-18 12:28 UTC, tkachukivan requested changes

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/elements.js
> +  nameTrialForm: document.querySelector('.form-trial__name'),
sometimes browser api can make your life easier
there is an api to work with forms and form elements by their names 
https://www.w3schools.com/jsref/coll_doc_forms.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +/* eslint-disable no-undef */
add elements to globals in eslint config

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +const namePattern = /^[a-zA-Z]+$/;
it is possible to create separate file for regexps

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +    let loopStart = ind === 0 ? 0 : 3;
it would be better to have separate arrays and listeners then hardcoded values like here

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +        validValueArr.push(validValue);
you don't use array elements after, so you can just change some variable to false and check later

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +  let validation = pattern.test(inputValue);
isValid would be more descriptive

2019-07-18 12:28 UTC, tkachukivan commented on HTML/mockup-axit/js/task1.js
> +    return false;
just add class when needed and return `validation`

2019-07-18 12:29 UTC, tkachukivan commented
don't have to do changes for elements file and new file for regexps

2019-07-23 08:39 UTC, tkachukivan approved these changes

2019-07-23 12:56 UTC, tsvetkovv approved these changes
I don't understand the profit function expression instead of function declaration.

2019-07-23 12:56 UTC, tsvetkovv commented on HTML/mockup-axit/js/task1.js
> +const inputNameArr1 = [
`trialFormInputs`?

2019-07-23 12:56 UTC, tsvetkovv commented on HTML/mockup-axit/js/task1.js
> +const patternArr1 = [pattern.name, pattern.email, pattern.password];
`trialFormPatterns`?

2019-07-24 10:21 UTC, merged