mockup axit task 2 - JS
maycatsby/ui-internship-lwo2 pull request #28
Opened 2019-07-24 12:37 UTC by maycatsby

https://maycatsby.github.io/ui-internship-lwo2/HTML/mockup-axit/

2019-07-26 13:27 UTC, tkachukivan requested changes
what about opacity animation for content :(

2019-07-26 13:27 UTC, tkachukivan commented on HTML/mockup-axit/js/content.js
> +export const paragraph = [
we have objects in js so why not use one structure like tab = { title: 'Title', description: 'sometext'}

2019-07-26 13:27 UTC, tkachukivan commented on HTML/mockup-axit/js/task2.js
> +    const elements = data;
destructuring?

2019-07-26 13:27 UTC, tkachukivan commented on HTML/mockup-axit/js/task2.js
> +      elements.tabs.forEach((el, index) => {
event delegation could be great technic to use here

2019-07-26 13:27 UTC, tkachukivan commented on HTML/mockup-axit/js/task2.js
> +          changeTabColor(e);
probably changeActiveTab would be better

2019-07-30 19:36 UTC, tsvetkovv requested changes
Storing static content in JS is not good idea. tab content should be placed in html, it also lets you to animate smoothly with opacity.
if you have objections/problems, ping me to discuss.

2019-07-30 19:36 UTC, Tsvetkovv commented on HTML/mockup-axit/js/task2.js
> +export const addingTabsEffects = () => {
`addTabsEffects`

2019-08-02 12:52 UTC, tkachukivan approved these changes

2019-08-05 15:14 UTC, tsvetkovv approved these changes
good

2019-08-06 12:23 UTC, merged