tasks 31-40
maycatsby/ui-internship-lwo2 pull request #4
Opened 2019-04-30 08:57 UTC by maycatsby

2019-04-30 10:17 UTC, mikhail-ev requested changes

2019-04-30 10:17 UTC, mikhail-ev commented on tasks/31_reverse-string-in-range/reverse-string-in-range.js
> +  return str.replace(middleEl, reverseEl);
won't work for case 'abcabc', [3, 6];

2019-04-30 10:17 UTC, mikhail-ev commented on tasks/33_array-plus-array/array-plus-array.js
> +  const longerArr = arr1.length > arr2.length ? arr1 : arr2;
I would recommend Math.max since you are using arr1[i] || 0

2019-04-30 10:17 UTC, mikhail-ev commented on tasks/36_row-weight/row-weight.js
> +  return arrOfWeight.map((cur) => {
if you have an array for each team it could be just a int variable, so this map isn't necessary

2019-04-30 10:17 UTC, mikhail-ev commented on tasks/36_row-weight/row-weight.js
> +    if (cur.length > 1) {
also you don't have to check the length in reduce if you would add an initial value, take a look on reduce signature

2019-04-30 10:17 UTC, mikhail-ev commented on tasks/37_min-number-to-prime/min-number-to-prime.js
> +  return numberToAdd;
won't work for [5, 2, 190].
probably the wrong algorithm has been used - it's a bad practice relying on hardcoded values especially in the case with infinite sets

2019-04-30 10:17 UTC, TargetTaiga commented on tasks/40_find-friend/find-friend.js
> +};
This is not an algorithmic way of solving the issue, I'd recommend solving this task with the following approach: take each group in the queue (it's 3 in our case) and check this groups hats.

2019-05-07 13:50 UTC, tkachukivan approved these changes
Just do Mike changes

2019-05-07 13:50 UTC, tkachukivan commented on tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
> +  return arrDigit.reverse();
why not then just chain this method to, also when you chain methods as above it is a good practice start every method from a new line, as it is easier to read
```
arr.toString()
  .split()
  .map()
  .reverse()
```

2019-05-07 13:50 UTC, tkachukivan commented on tasks/36_row-weight/row-weight.js
> +  for (let i = 0; i < arr.length; i++) {
you can solve it with just one reduce method with less complexity

2019-05-07 13:50 UTC, tkachukivan commented on tasks/39_unique-in-order/unique-in-order.js
> +  let arrOfArg = [...arg];
it is better to use split method for strings instead of `....`

2019-06-06 09:31 UTC, mikhail-ev approved these changes

2019-07-12 07:23 UTC, merged