task 71-80
maycatsby/ui-internship-lwo2 pull request #8
Opened 2019-05-10 07:02 UTC by maycatsby

2019-05-10 14:45 UTC, tsvetkovv approved these changes
Approve with suggestions

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/71_binary-encode/binary-encode.js
> +    let toBin = str.charCodeAt(i).toString(2);
1. Use `const` by default
2. Use `let` if you have to rebind a variable

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/72_carrying/carrying.js
> +  let isNotNum = args.filter((cur) => typeof(cur) !== 'number').length;
More useful `every` method of array here.
And `isNotNum` not good name for number variable. if it's counter, better to name 'wrongArgumentCount'.
In most cases prefix `is` is used for boolean variable

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/74_dna-pairing/dna-pairing.js
> +  const dnaPair = [['A', 'T'], ['T', 'A'], ['C', 'G'], ['G', 'C']];
FYI: you can declare as object (map) where key is first letter and value is second letter.

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/74_dna-pairing/dna-pairing.js
> +    for (let i = 0; i < dnaPair.length; i++) {
You can use `dnaPair.find` method to find specific item.

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/76_deep-object-clone/deep-object-clone.js
> +  for (let i = 0; i < keysArr.length; i++) {
you can use `forEach` method to traverse through array of keys

2019-05-10 14:45 UTC, tsvetkovv commented on tasks/78_valid-braces/valid-braces.js
> +    if (bracesOpen.indexOf(cur) !== -1) {
FYI: `bracesOpen.includes(cur)`

2019-05-10 15:12 UTC, Tsvetkovv commented on tasks/71_binary-encode/binary-encode.js
> +    let zerosRepeats = 8 - toBin.length;
`padStart` method on string?

2019-05-13 09:08 UTC, tkachukivan requested changes
fix 76 task to get approve :)

2019-05-13 09:08 UTC, tkachukivan commented on tasks/71_binary-encode/binary-encode.js
> +  let binStr = [];
looks like a perfect place for `Array.prototype.map` method

2019-05-13 09:08 UTC, tkachukivan commented on tasks/74_dna-pairing/dna-pairing.js
> +    for (let i = 0; i < dnaPair.length; i++) {
or if you use map from previous comment you can just get item from this map

2019-05-13 09:08 UTC, tkachukivan commented on tasks/75_complementary-dna/complementary-dna.js
> +  const dnaPair = [['A', 'T'], ['T', 'A'], ['C', 'G'], ['G', 'C']];
same as above with map

2019-05-13 09:08 UTC, tkachukivan commented on tasks/76_deep-object-clone/deep-object-clone.js
> +    copyObject[keysArr[i]] = deepClone(arg[keysArr[i]]);
this will not work in fact you just assign to every key a new object but not old value, you need to run recursive function only when you have an object as value of key

2019-05-13 09:08 UTC, tkachukivan commented on tasks/78_valid-braces/valid-braces.js
> +  const bracesClose = [')', ']', '}'];
you can use map here instead of two arrays

2019-05-13 09:08 UTC, tkachukivan commented on tasks/78_valid-braces/valid-braces.js
> +      stack.splice(-1);
pop method looks much better here

2019-05-13 09:08 UTC, tkachukivan commented on tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
> +    for (let i = 2; i <= parseInt(Math.sqrt(j)) && prime; i++) {
looks like a code which can be replaced to separate function which you will call in if with current j

2019-05-16 07:56 UTC, tkachukivan approved these changes

2019-05-16 07:56 UTC, tkachukivan commented on tasks/76_deep-object-clone/deep-object-clone.js
> +    if (arg[keysArr[i]] !== null && typeof arg[keysArr[i]] === 'object') {
it would be a bit better to have `forEach` here as Viktor write before, or maybe `for of` as it is a bit hard to read like this

2019-05-28 08:57 UTC, merged